config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root to: "flats#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :destroy]

  def index
    @flats = Flat.all
  end

  def show
    @flat = set_flat
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(set_flat)
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Awesome expensive flats</h1>
<div class="grid">
  <% @flats.each do |flat| %>
    <%= link_to flat_path(flat) do %>
    <div class="card">
      <h4><%= flat.name %></h4>
      <p><%= flat.address %></p>
      <p><%= flat.description.truncate(20) %></p>
      <p><%= flat.price_per_night %></p>
      <p><%= flat.number_of_guests %></p>
    </div>
    <% end %>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>Add a flat</h1>

<%= form_with model: @flat do|f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>
   <%= f.label :address %>
   <%= f.text_field :address %>
   <%= f.label :description %>
   <%= f.text_field :description %>
   <%= f.label :price_per_night %>
   <%= f.number_field :price_per_night %>
   <%= f.label :number_of_guests %>
   <%= f.number_field :number_of_guests %>
   <%= f.submit%>
<%end%>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<div>
  <p><%= @flat.address %></p>
  <p><%= @flat.description %></p>
  <p><%= @flat.price_per_night %></p>
  <p><%= @flat.number_of_guests %></p>

  <%= link_to "Delete",
  flat_path(@flat),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>
<%= link_to "See all flats", flats_path %>
<%= link_to "Add a flat", new_flat_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>